<a href="https://colab.research.google.com/github/KirtiRanjan26/Numpy-Full-tutorial/blob/main/assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Assignment

### Assignment 1: Array Creation and Manipulation

In [ ]:
# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
import numpy as np
arr=np.random.randint(1,21,size=(5,5))
print("The array is:",arr)
print("after replacement:")
arr[:, 2] = 1 # replacement
print(arr)
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.
arr2= np.random.randint(1,17,size=(4,4))
print("next array is",arr2)
print("after replacement:")
np.fill_diagonal(arr,0)
print(arr)
print("replace bothside:")
np.fill_diagonal(np.fliplr(arr), 0)
print(arr)

The array is: [[ 5 14 19 20 20]
 [ 4 20 10  6 10]
 [ 2  9 14 11  7]
 [ 3  7  9  8 12]
 [ 3  4  5  5 18]]
after replacement:
[[ 5 14  1 20 20]
 [ 4 20  1  6 10]
 [ 2  9  1 11  7]
 [ 3  7  1  8 12]
 [ 3  4  1  5 18]]
next array is [[ 4 11  7  2]
 [11 12  5  9]
 [11 13  1  5]
 [12 10  5 11]]
after replacement:
[[ 0 14  1 20 20]
 [ 4  0  1  6 10]
 [ 2  9  0 11  7]
 [ 3  7  1  0 12]
 [ 3  4  1  5  0]]
replace bothside:
[[ 0 14  1 20  0]
 [ 4  0  1  0 10]
 [ 2  9  0 11  7]
 [ 3  0  1  0 12]
 [ 0  4  1  5  0]]


### Assignment 2: Array Indexing and Slicing

In [ ]:
'''1. Create a NumPy array of shape (6, 6) with values from 1 to 36.
 Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.'''
import numpy as np
arr=np.random.randint(1,37,size=(6,6))
print(arr)
print("extracting subarray:")
print(arr[2:5,1:4])



#2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
import numpy as np
arr2=np.random.randint(1,37,size=(5,5))
print(arr2)
print("extracting element on the border:")
Border=np.concatenate([
    arr2[0,:],
    arr2[-1,:],
    arr2[1:-1,0],
    arr2[1:-1,-1]
])
print(Border.reshape(4,4))



[[ 4 36 24  5  6 23]
 [ 5  8 15  7 17  2]
 [12 19 22 26 10 26]
 [26  7 31  8  2 11]
 [ 6 35  7 23 32  9]
 [13 16  8  1 17 28]]
extracting subarray:
[[19 22 26]
 [ 7 31  8]
 [35  7 23]]
[[ 6 27  8 13 32]
 [32 12 22 34 27]
 [15 24 13 24 23]
 [32 19 30  1 13]
 [ 3 33  4 27  5]]
extracting element on the border:
[[ 6 27  8 13]
 [32  3 33  4]
 [27  5 32 15]
 [32 27 23 13]]


### Assignment 3: Array Operations


In [ ]:
''' 1. Create two NumPy arrays of shape (3, 4) filled with random integers.
Perform element-wise addition, subtraction, multiplication, and division.'''
import numpy as np
arr=np.random.randint(1,16,size=(3,4))
arr2=np.random.randint(1,16,size=(3,4))
print("addtion:",np.add(arr,arr2))
print("substraction:",np.subtract(arr,arr2))
print("division:",np.divide(arr,arr2))
print("multiplication:",np.multiply(arr,arr2))
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

arr = np.arange(1, 17).reshape(4, 4)
print("Array:\n", arr)

# Row-wise sum
row_sum = np.sum(arr, axis=1)
print("\nRow-wise sum:", row_sum)

# Column-wise sum
col_sum = np.sum(arr, axis=0)
print("Column-wise sum:", col_sum)

addtion: [[23 13  6 18]
 [12 17 26 19]
 [19 25  7 23]]
substraction: [[ 7  1 -2 -2]
 [ 0 -7  4 -5]
 [ 5  3 -3  7]]
division: [[1.875      1.16666667 0.5        0.8       ]
 [1.         0.41666667 1.36363636 0.58333333]
 [1.71428571 1.27272727 0.4        1.875     ]]
multiplication: [[120  42   8  80]
 [ 36  60 165  84]
 [ 84 154  10 120]]
Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Row-wise sum: [10 26 42 58]
Column-wise sum: [28 32 36 40]
