<a href="https://colab.research.google.com/github/KirtiRanjan26/Numpy-Full-tutorial/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The numpy library for Scientific computing in python. its provide a high perfromance multidimentional array object.

In [4]:
import numpy as np

In [3]:
#creation of an numpy array.
a =np. array([1,2,3])
print(a)
print(type(a))
print(a.dtype)
print(np.array([1.2,2.3,3.4]))
b=np.array([(24,56,78),(12,45,30)])# 2D array
print(b)
# check the dimention
b.shape
#change the datatype of an element in the array
c=np.array([(1.4,56,76,43),(2.5,11,87,29)],dtype=float)
print(c)

NameError: name 'np' is not defined

In [ ]:
# initial placeholder
np.zeros((3,4)) # create an array of Zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,4))# create an array of ones
# arr= np.arange(10,25,3,dtype=float) # creating array of range
# print(arr)
arr=np.arange(8,5,9)
print(arr)


[]


In [ ]:
np.linspace(0,2,9)# print 9 number from 0 to 2 .you spasify the number of element in between start and stop

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
np.full((2,4),7)# similar number of array print

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
np.random.random((4,5)) # always start from zero and end with zero
arr=np.random.randint(2,51,size=10) # print 1D array of  random number from 2 to 50 with number of element is 10
print(arr)
arr2= np.random.uniform(2,30,size=12) # print foating number of 1D array
print(arr2)
arr3 = np.random.randint(2,41,size=(3,5)) #random number of 3x4 array
print(arr3)


[19 15 27  8 44 20 41 18 36 13]
[ 4.27382084 14.6700688  29.60892608 14.97192576 14.39843219  5.28948483
  8.98422264  7.02341163 17.17533597 28.76700617 23.65194041 21.39380255]
[[18  6 22 32  6]
 [11 19 23  4 32]
 [36 12 16 37 31]]
arr4= None


##arithmatic operation

In [ ]:
# addition of two matrix
arr1= np.random.randint(2,24,size=5)
print(arr1)
arr2= np.random.randint(4,25,size=5)
print(arr2)
c=arr1+arr2
print("add the number",c)
c=np.add(arr1,arr2)
print(c)

[11 12  8 16 17]
[15 16 17 11 14]
add the number [26 28 25 27 31]
[26 28 25 27 31]


In [ ]:
#substraction
arr1=np.random.randint(12,34,size=(2,3))
arr2=np.random.randint(12,34,size=(2,3))
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[  1  12 -15]
 [  2  -7   6]]
[[  1  12 -15]
 [  2  -7   6]]


In [ ]:
# multiplication
arr1=np.full((4,3),6)
arr2= np.full((4,3),4)
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[24 24 24]
 [24 24 24]
 [24 24 24]
 [24 24 24]]
[[24 24 24]
 [24 24 24]
 [24 24 24]
 [24 24 24]]


In [ ]:
#division
arr1=np.random.randint(12,34,size=(2,3))
arr2=np.random.randint(12,34,size=(2,3))
print(arr1/arr2)
print(np.divide(arr1,arr2))

[[0.92       1.         1.35714286]
 [1.5        1.         0.59259259]]
[[0.92       1.         1.35714286]
 [1.5        1.         0.59259259]]


In [ ]:
#Exponentiation
arr1=np.random.randint(12,34,size=(2,3))
print(np.exp(arr1))


[[3.58491285e+09 5.32048241e+11 4.42413392e+05]
 [7.89629602e+13 2.90488497e+13 1.06864746e+13]]


In [ ]:
arr1=np.full((2,4),7)
print(np.sqrt(arr1))

[[2.64575131 2.64575131 2.64575131 2.64575131]
 [2.64575131 2.64575131 2.64575131 2.64575131]]


## Comparision

In [ ]:
# elementwise comparision
arr1=np.zeros((2,3))
arr1=np.zeros((2,3))
print((arr1==arr2))
arr3=np.ones((2,4))
print((arr1<arr2))

[[False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]]


In [ ]:
#arraywise comparision (dimensionwise equal or not)
arr1=np.zeros((2,3))
arr2=np.zeros((2,3))
arr3=np.ones((2,4))
print(np.array_equal(arr1,arr2))
print(np.array_equal(arr1,arr3))



True
False


## Aggregate function


In [7]:
arr=np.random.randint(2,12,size=(2,3))
print(arr)
print(arr.sum()) # sum of all element
print(arr.min(axis=1)) # minimum element in each row
print(arr.max(axis=1)) # maximum element in each column
print(arr.min()) # print the single minimum  element entire array
print(arr.cumsum()) # cumulative sum


[[11 11  6]
 [ 4 10  7]]
49
[6 4]
[11 10]
4
[11 22 28 32 42 49]


### cumulative sum
arr=[12,12,3]
arr.cumsum()
1-->12
2-->12+12=24
3-->24+3=27
final = [12,24,27]

In [9]:
print(arr.mean()) # mean
import numpy as np

arr = np.array([7, 1, 5, 2, 9,10])
median_value = np.median(arr)
print(median_value)
print(np.std(arr)) # standard deviation
print(np.var(arr))




5.666666666666667
6.0
3.3499585403736303
11.222222222222223


## subsetting, Indexing ,Slicing

In [12]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60])



In [20]:
#Get the first 3 elements.
print(arr[:3])

#Get the last 2 elements.
print(arr[-2:])

#Get every alternate element.
print(arr[::2])

#Get elements greater than 30.
print(arr[arr>30])

#Get elements from index 1 to 4 (inclusive).
print(arr[1:5])

[10 20 30]
[50 60]
[10 30 50]
[40 50 60]
[20 30 40 50]


In [21]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])


In [41]:
#Extract the element at row 2, column 3.
print(arr2[1,2])

#Extract the first row.
print(arr2[0])

#Extract the first column.
print(arr2[:,0])

#Extract the subarray [[5, 6], [8, 9]].
print(arr2[1:3,1:3])
#Extract the subarray [[1, 2], [7, 8]].
print(arr2[0:3:2,0:2])
#Extract the subarray [[1, 3], [7, 9]].
print(arr2[:3:2,:3:2])


#Extract all elements greater than 5.
print(arr2[arr2>5])
# convert all element to float
print(arr2.astype(float))
print(arr2.astype(str))
print(arr2)

6
[1 2 3]
[1 4 7]
[[5 6]
 [8 9]]
[[1 2]
 [7 8]]
[[1 3]
 [7 9]]
[6 7 8 9]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
# reverse  array
print(arr[::-1])# 1D array
print(arr2[::-1,::-1])# 2D array


[60 50 40 30 20 10]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [46]:
# fancy indexing
arr = np.array([10, 20, 30, 40, 50])
#   # Positions we want
# i want to print 10,20,40
index=[0,1,3]
print(arr[index])


[10 20 40]


In [49]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

  # Picks (0,1)=2 and (2,2)=9
print(arr2[[0, 2], [1, 2]])
# first write the codinate number of element example (0,1)=2
# i want 5 then 5=(1,1)
print(arr2[1,1])
# i want 7 and 6
# 7=(2,0) and 6=(1,2)
print(arr2[[2,1],[0,2]])


[2 9]
5
[7 6]


In [54]:
# adding and removing element
new=np.insert(arr2,7,5)
new=np.insert(new,7,12)
print(new.resize((3,4)))

None
