<a href="https://colab.research.google.com/github/KirtiRanjan26/Numpy-Full-tutorial/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The numpy library for Scientific computing in python. its provide a high perfromance multidimentional array object.

In [ ]:
import numpy as np

In [ ]:
#creation of an numpy array.
a =np. array([1,2,3])
print(a)
print(type(a))
print(a.dtype)
print(np.array([1.2,2.3,3.4]))
b=np.array([(24,56,78),(12,45,30)])# 2D array
print(b)
# check the dimention
b.shape
#change the datatype of an element in the array
c=np.array([(1.4,56,76,43),(2.5,11,87,29)],dtype=float)
print(c)

[1 2 3]
<class 'numpy.ndarray'>
int64
[1.2 2.3 3.4]
[[24 56 78]
 [12 45 30]]
[[ 1.4 56.  76.  43. ]
 [ 2.5 11.  87.  29. ]]


In [ ]:
# initial placeholder
np.zeros((3,4)) # create an array of Zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((2,4))# create an array of ones
arr= np.arange(10,25,3,dtype=float) # creating array of range
print(arr)

[10. 13. 16. 19. 22.]


In [ ]:
np.linspace(0,2,9)# print 9 number from 0 to 2 .you spasify the number of element in between start and stop

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
np.full((2,4),7)# similar number of array print

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
np.random.random((4,5)) # always start from zero and end with zero
arr=np.random.randint(2,51,size=10) # print 1D array of  random number from 2 to 50 with number of element is 10
print(arr)
arr2= np.random.uniform(2,30,size=12) # print foating number of 1D array
print(arr2)
arr3 = np.random.randint(2,41,size=(3,5)) #random number of 3x4 array
print(arr3)


[19 15 27  8 44 20 41 18 36 13]
[ 4.27382084 14.6700688  29.60892608 14.97192576 14.39843219  5.28948483
  8.98422264  7.02341163 17.17533597 28.76700617 23.65194041 21.39380255]
[[18  6 22 32  6]
 [11 19 23  4 32]
 [36 12 16 37 31]]
arr4= None
